### ISSUE TITLE
Absence of MethodEntry library

### ISSUE THREAD

**Issue by RainM** [apangin/helfy#3]
Hi!

I've tried to run MethodEntry test but I got UnsatisfiedLinkError exception with the following exception:

Exception in thread "main" java.lang.UnsatisfiedLinkError: no MethodEntry in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at one.helfy.MethodEntry.main(MethodEntry.java:78)

I believe the issue cause is just absence of this native library with the only one symbol 'rdtsc', right? I think it worth to add sources for this library somewhere in this project.

--Sergey

**Comment by apangin** [comment]
You are right. I will add the missing native library code.

**Comment by apangin** [comment]
Pushed MethodEntry.c
